version: '3.7'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    hostname: react-process-manager-php
    container_name: react-process-manager-php
    ports:
      - 4242:4242
    volumes:
      - ./:/var/www/html
